### ISSUE TITLE
So how do I actually download and run this app?

### ISSUE THREAD

**Issue by LeoStaley** [IxxyXR/wythoff-polyhedra#1]
I'm not a programmer. The apps I use that I have found on githum usually have a dedicated download link to the most updated, executable version of the app. I don't know how I would run this if I downloaded the repository.

**Comment by andybak** [comment]
Have you checked the releases page?: https://github.com/IxxyXR/Polyhydra/releases

(Standard place to look on GitHub)

Also - we're on itch.io which might be easier for you.
